[green_agent]
endpoint = "http://green-agent:9009"

[[participants]]
role = "purple_agent"
endpoint = "http://purple_agent:9009"

[config]
domain = "browsergym"
timeout_seconds = 120
max_steps = 10
max_tasks_per_benchmark = 2
headless = true


[[benchmarks]]
id = "miniwob"

[[benchmarks]]
id = "assistantbench"